# Generated by Django 5.0.7 on 2024-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='аватар', null=True, upload_to='media/users_avatar', verbose_name='аватар'),
        ),
    ]
