# Generated by Django 5.0.7 on 2024-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile_app', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='профиль telegram', max_length=250, null=True, unique=True, verbose_name='профиль telegram'),
        ),
    ]
