services:
  db:
    container_name: "db"
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - ./data/db:/var/lib/postgresql/data

  bot:
    container_name: "telegram_bot"
    build: .
    restart: always
    volumes:
      - .:/app
    networks:
      - custom
    command: >
      python tg_bot/run.py

  web:
    container_name: "django_app"
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - custom
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  custom:
    driver: bridge