# Generated by Django 5.0.7 on 2024-08-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_atlas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Иллюстрация')),
                ('description', models.CharField(max_length=255, verbose_name='Комментарий к изображению')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_atlas_app.placement', verbose_name='Укладка')),
            ],
        ),
    ]
