# Generated by Django 5.0.7 on 2024-08-01 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_atlas_app', '0002_remove_placement_image_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api_atlas_app.placement', verbose_name='Укладка'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
