# Generated by Django 5.0.7 on 2024-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_atlas_app', '0003_alter_image_placement_alter_placement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к изображению'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.FileField(upload_to='media/images', verbose_name='Иллюстрация'),
        ),
    ]
