# Generated by Django 5.0.7 on 2024-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_atlas_app', '0004_alter_image_description_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.FileField(upload_to='images', verbose_name='Иллюстрация'),
        ),
    ]
